import type { Emergency, Vehicle, Incident, Route, Trajectory } from './api/types'

export const DEMO_VEHICLES: Vehicle[] = [
  {
    id: 'veh-amb-01',
    vehicleId: 'AMB-01',
    registrationNumber: 'KA-01-EA-1001',
    type: 'AMBULANCE',
    status: 'EN_ROUTE',
    driverName: 'Ramesh Gowda',
    driverContact: '+91 98450 11001',
    capacity: 2,
    location: { type: 'Point', coordinates: [77.6271, 12.9352] },
    speed: 46.0,
    heading: 42,
    hospitalName: 'Manipal Hospital (Old Airport Rd)',
    hospitalCode: 'MAN-01',
  },
  {
    id: 'veh-amb-02',
    vehicleId: 'AMB-02',
    registrationNumber: 'KA-04-EA-2002',
    type: 'AMBULANCE',
    status: 'EN_ROUTE',
    driverName: 'Suresh Kumar',
    driverContact: '+91 98450 22002',
    capacity: 2,
    location: { type: 'Point', coordinates: [77.5925, 13.0358] },
    speed: 42.0,
    heading: 175,
    hospitalName: 'Victoria Hospital',
    hospitalCode: 'VIC-01',
  },
  {
    id: 'veh-amb-03',
    vehicleId: 'AMB-03',
    registrationNumber: 'KA-03-EA-3003',
    type: 'AMBULANCE',
    status: 'EN_ROUTE',
    driverName: 'Priya Sharma',
    driverContact: '+91 98450 33003',
    capacity: 2,
    location: { type: 'Point', coordinates: [77.7500, 12.9698] },
    speed: 34.0,
    heading: 250,
    hospitalName: 'Sakra World Hospital',
    hospitalCode: 'SAK-01',
  },
  {
    id: 'veh-amb-04',
    vehicleId: 'AMB-04',
    registrationNumber: 'KA-50-EA-4004',
    type: 'AMBULANCE',
    status: 'EN_ROUTE',
    driverName: 'Anil Reddy',
    driverContact: '+91 98450 44004',
    capacity: 1,
    location: { type: 'Point', coordinates: [77.5963, 13.1007] },
    speed: 55.0,
    heading: 180,
    hospitalName: 'Bowring Hospital',
    hospitalCode: 'BOW-01',
  },
  {
    id: 'veh-amb-05',
    vehicleId: 'AMB-05',
    registrationNumber: 'KA-51-EA-5005',
    type: 'AMBULANCE',
    status: 'EN_ROUTE',
    driverName: 'Deepak Hegde',
    driverContact: '+91 98450 55005',
    capacity: 2,
    location: { type: 'Point', coordinates: [77.6766, 12.8452] },
    speed: 25.0,
    heading: 320,
    hospitalName: 'St John\'s Hospital',
    hospitalCode: 'STJ-01',
  },
  {
    id: 'veh-amb-06',
    vehicleId: 'AMB-06',
    registrationNumber: 'KA-05-EA-6006',
    type: 'AMBULANCE',
    status: 'AVAILABLE',
    driverName: 'Kavita Rao',
    driverContact: '+91 98450 66006',
    capacity: 2,
    location: { type: 'Point', coordinates: [77.6250, 12.9300] },
    speed: 0,
    heading: 0,
    hospitalName: 'St John\'s Hospital (Standby Bay)',
    hospitalCode: 'STJ-01',
  },
  {
    id: 'veh-amb-07',
    vehicleId: 'AMB-07',
    registrationNumber: 'KA-02-EA-7007',
    type: 'AMBULANCE',
    status: 'DISPATCHED',
    driverName: 'Manjunath B',
    driverContact: '+91 98450 77007',
    capacity: 1,
    location: { type: 'Point', coordinates: [77.6412, 12.9784] },
    speed: 38.0,
    heading: 120,
    hospitalName: 'Manipal Hospital',
    hospitalCode: 'MAN-01',
  },
  {
    id: 'veh-amb-08',
    vehicleId: 'AMB-08',
    registrationNumber: 'KA-41-EA-8008',
    type: 'AMBULANCE',
    status: 'AVAILABLE',
    driverName: 'Kiran Patel',
    driverContact: '+91 98450 88008',
    capacity: 2,
    location: { type: 'Point', coordinates: [77.5684, 13.0305] },
    speed: 0,
    heading: 0,
    hospitalName: 'Ramaiah Memorial Hospital',
    hospitalCode: 'RMH-01',
  },
  {
    id: 'veh-amb-09',
    vehicleId: 'AMB-09',
    registrationNumber: 'KA-01-EA-9009',
    type: 'AMBULANCE',
    status: 'AT_SCENE',
    driverName: 'Shweta Singh',
    driverContact: '+91 98450 99009',
    capacity: 2,
    location: { type: 'Point', coordinates: [77.6389, 12.9116] },
    speed: 0,
    heading: 90,
    hospitalName: 'St John\'s Hospital',
    hospitalCode: 'STJ-01',
  },
  {
    id: 'veh-amb-10',
    vehicleId: 'AMB-10',
    registrationNumber: 'KA-03-EA-1010',
    type: 'AMBULANCE',
    status: 'EN_ROUTE',
    driverName: 'Imran Khan',
    driverContact: '+91 98450 10100',
    capacity: 2,
    location: { type: 'Point', coordinates: [77.7011, 12.9592] },
    speed: 48.0,
    heading: 210,
    hospitalName: 'Sakra World Hospital',
    hospitalCode: 'SAK-01',
  },
  {
    id: 'veh-amb-11',
    vehicleId: 'AMB-11',
    registrationNumber: 'KA-05-EA-1111',
    type: 'AMBULANCE',
    status: 'EN_ROUTE',
    driverName: 'Rajeshwari N',
    driverContact: '+91 98450 11110',
    capacity: 1,
    location: { type: 'Point', coordinates: [77.5833, 12.9298] },
    speed: 38.0,
    heading: 350,
    hospitalName: 'Victoria Hospital',
    hospitalCode: 'VIC-01',
  },
  {
    id: 'veh-amb-12',
    vehicleId: 'AMB-12',
    registrationNumber: 'KA-05-EA-1212',
    type: 'AMBULANCE',
    status: 'DISPATCHED',
    driverName: 'Arun Kumar',
    driverContact: '+91 98450 12120',
    capacity: 2,
    location: { type: 'Point', coordinates: [77.5855, 12.9063] },
    speed: 40.0,
    heading: 190,
    hospitalName: 'Fortis Hospital (Bannerghatta)',
    hospitalCode: 'APO-01',
  },
  {
    id: 'veh-amb-13',
    vehicleId: 'AMB-13',
    registrationNumber: 'KA-02-EA-1313',
    type: 'AMBULANCE',
    status: 'EN_ROUTE',
    driverName: 'Preeti Deshmukh',
    driverContact: '+91 98450 13130',
    capacity: 2,
    location: { type: 'Point', coordinates: [77.5550, 12.9980] },
    speed: 52.0,
    heading: 30,
    hospitalName: 'Bangalore Baptist Hospital',
    hospitalCode: 'BBH-01',
  },
  {
    id: 'veh-amb-14',
    vehicleId: 'AMB-14',
    registrationNumber: 'KA-04-EA-1414',
    type: 'AMBULANCE',
    status: 'AVAILABLE',
    driverName: 'Venkatesh Prasad',
    driverContact: '+91 98450 14140',
    capacity: 1,
    location: { type: 'Point', coordinates: [77.6033, 12.9833] },
    speed: 0,
    heading: 0,
    hospitalName: 'Bowring Hospital (Standby)',
    hospitalCode: 'BOW-01',
  },
  {
    id: 'veh-amb-15',
    vehicleId: 'AMB-15',
    registrationNumber: 'KA-02-EA-1515',
    type: 'AMBULANCE',
    status: 'MAINTENANCE',
    driverName: 'Ganesh Pai',
    driverContact: '+91 98450 15150',
    capacity: 2,
    location: { type: 'Point', coordinates: [77.5180, 13.0280] },
    speed: 0,
    heading: 0,
    hospitalName: 'Peenya Fleet Service Station',
    hospitalCode: 'DEPOT-01',
  },
  {
    id: 'veh-amb-16',
    vehicleId: 'AMB-16',
    registrationNumber: 'KA-51-EA-1616',
    type: 'AMBULANCE',
    status: 'AVAILABLE',
    driverName: 'Mohammed Zeeshan',
    driverContact: '+91 98450 16160',
    capacity: 2,
    location: { type: 'Point', coordinates: [77.6890, 12.9288] },
    speed: 0,
    heading: 0,
    hospitalName: 'Sakra World Hospital',
    hospitalCode: 'SAK-01',
  },
  {
    id: 'veh-amb-17',
    vehicleId: 'AMB-17',
    registrationNumber: 'KA-05-EA-1717',
    type: 'AMBULANCE',
    status: 'AVAILABLE',
    driverName: 'Raghavendra Rao',
    driverContact: '+91 98450 17170',
    capacity: 2,
    location: { type: 'Point', coordinates: [77.5560, 12.9250] },
    speed: 0,
    heading: 0,
    hospitalName: 'Sagar Hospitals Banashankari',
    hospitalCode: 'SAG-01',
  },
  {
    id: 'veh-amb-18',
    vehicleId: 'AMB-18',
    registrationNumber: 'KA-01-EA-1818',
    type: 'AMBULANCE',
    status: 'EN_ROUTE',
    driverName: 'Manjunath Gowda',
    driverContact: '+91 98450 18180',
    capacity: 2,
    location: { type: 'Point', coordinates: [77.6100, 12.9150] },
    speed: 44.0,
    heading: 75,
    hospitalName: 'Jayadeva Institute of Cardiology',
    hospitalCode: 'JAY-01',
  },
  {
    id: 'veh-amb-19',
    vehicleId: 'AMB-19',
    registrationNumber: 'KA-02-EA-1919',
    type: 'AMBULANCE',
    status: 'DISPATCHED',
    driverName: 'Santosh Patil',
    driverContact: '+91 98450 19190',
    capacity: 1,
    location: { type: 'Point', coordinates: [77.5380, 12.9710] },
    speed: 36.0,
    heading: 85,
    hospitalName: 'Victoria Hospital (City Market)',
    hospitalCode: 'VIC-01',
  },
  {
    id: 'veh-amb-20',
    vehicleId: 'AMB-20',
    registrationNumber: 'KA-04-EA-2020',
    type: 'AMBULANCE',
    status: 'AVAILABLE',
    driverName: 'Naveen Kumar',
    driverContact: '+91 98450 20200',
    capacity: 2,
    location: { type: 'Point', coordinates: [77.6480, 13.0180] },
    speed: 0,
    heading: 0,
    hospitalName: 'Specialist Hospital Kalyan Nagar',
    hospitalCode: 'SPE-01',
  },
  {
    id: 'veh-amb-21',
    vehicleId: 'AMB-21',
    registrationNumber: 'KA-41-EA-2121',
    type: 'AMBULANCE',
    status: 'EN_ROUTE',
    driverName: 'Harish Babu',
    driverContact: '+91 98450 21210',
    capacity: 2,
    location: { type: 'Point', coordinates: [77.4850, 12.9150] },
    speed: 50.0,
    heading: 60,
    hospitalName: 'BGS Gleneagles Global Hospital',
    hospitalCode: 'BGS-01',
  },
  {
    id: 'veh-amb-22',
    vehicleId: 'AMB-22',
    registrationNumber: 'KA-02-EA-2222',
    type: 'AMBULANCE',
    status: 'AVAILABLE',
    driverName: 'Prashanth Hegde',
    driverContact: '+91 98450 22220',
    capacity: 1,
    location: { type: 'Point', coordinates: [77.5500, 13.0220] },
    speed: 0,
    heading: 0,
    hospitalName: 'Sparsh Hospital Yeshwanthpur',
    hospitalCode: 'SPA-01',
  },
  {
    id: 'veh-amb-23',
    vehicleId: 'AMB-23',
    registrationNumber: 'KA-53-EA-2323',
    type: 'AMBULANCE',
    status: 'DISPATCHED',
    driverName: 'Vinayaka Prasad',
    driverContact: '+91 98450 23230',
    capacity: 2,
    location: { type: 'Point', coordinates: [77.6960, 13.0020] },
    speed: 35.0,
    heading: 140,
    hospitalName: 'Manipal Hospital Whitefield',
    hospitalCode: 'MAN-02',
  },
  {
    id: 'veh-amb-24',
    vehicleId: 'AMB-24',
    registrationNumber: 'KA-51-EA-2424',
    type: 'AMBULANCE',
    status: 'EN_ROUTE',
    driverName: 'Karthik Swamy',
    driverContact: '+91 98450 24240',
    capacity: 2,
    location: { type: 'Point', coordinates: [77.6820, 12.9080] },
    speed: 42.0,
    heading: 310,
    hospitalName: 'Columbia Asia Hospital Sarjapur',
    hospitalCode: 'COL-01',
  },
  {
    id: 'veh-amb-25',
    vehicleId: 'AMB-25',
    registrationNumber: 'KA-05-EA-2525',
    type: 'AMBULANCE',
    status: 'AVAILABLE',
    driverName: 'Chetan Murthy',
    driverContact: '+91 98450 25250',
    capacity: 2,
    location: { type: 'Point', coordinates: [77.5740, 12.9420] },
    speed: 0,
    heading: 0,
    hospitalName: 'KIMS Hospital Basavanagudi',
    hospitalCode: 'KIM-01',
  },
  {
    id: 'veh-amb-26',
    vehicleId: 'AMB-26',
    registrationNumber: 'KA-04-EA-2626',
    type: 'AMBULANCE',
    status: 'EN_ROUTE',
    driverName: 'Mohammed Farhan',
    driverContact: '+91 98450 26260',
    capacity: 1,
    location: { type: 'Point', coordinates: [77.6120, 12.9980] },
    speed: 38.0,
    heading: 195,
    hospitalName: 'Bowring Hospital',
    hospitalCode: 'BOW-01',
  },
  {
    id: 'veh-amb-27',
    vehicleId: 'AMB-27',
    registrationNumber: 'KA-01-EA-2727',
    type: 'AMBULANCE',
    status: 'DISPATCHED',
    driverName: 'Divakar Naik',
    driverContact: '+91 98450 27270',
    capacity: 2,
    location: { type: 'Point', coordinates: [77.6480, 12.9550] },
    speed: 40.0,
    heading: 260,
    hospitalName: 'Command Hospital Air Force',
    hospitalCode: 'CMD-01',
  },
  {
    id: 'veh-amb-28',
    vehicleId: 'AMB-28',
    registrationNumber: 'KA-41-EA-2828',
    type: 'AMBULANCE',
    status: 'AVAILABLE',
    driverName: 'Lokesh Gowda',
    driverContact: '+91 98450 28280',
    capacity: 2,
    location: { type: 'Point', coordinates: [77.5080, 12.9620] },
    speed: 0,
    heading: 0,
    hospitalName: 'Fortis Hospital Rajajinagar',
    hospitalCode: 'FOR-02',
  },
  {
    id: 'veh-amb-29',
    vehicleId: 'AMB-29',
    registrationNumber: 'KA-53-EA-2929',
    type: 'AMBULANCE',
    status: 'EN_ROUTE',
    driverName: 'Sridhar Reddy',
    driverContact: '+91 98450 29290',
    capacity: 2,
    location: { type: 'Point', coordinates: [77.6950, 12.9850] },
    speed: 45.0,
    heading: 230,
    hospitalName: 'Rainbow Children\'s Hospital',
    hospitalCode: 'RAI-01',
  },
  {
    id: 'veh-amb-30',
    vehicleId: 'AMB-30',
    registrationNumber: 'KA-03-EA-3030',
    type: 'AMBULANCE',
    status: 'AVAILABLE',
    driverName: 'Sunil Thomas',
    driverContact: '+91 98450 30300',
    capacity: 2,
    location: { type: 'Point', coordinates: [77.6400, 13.0100] },
    speed: 0,
    heading: 0,
    hospitalName: 'Aster CMI Hospital',
    hospitalCode: 'AST-01',
  },
  {
    id: 'veh-amb-31',
    vehicleId: 'AMB-31',
    registrationNumber: 'KA-04-EA-3131',
    type: 'AMBULANCE',
    status: 'DISPATCHED',
    driverName: 'Jagdish Chandra',
    driverContact: '+91 98450 31310',
    capacity: 1,
    location: { type: 'Point', coordinates: [77.5920, 13.0250] },
    speed: 46.0,
    heading: 15,
    hospitalName: 'Bangalore Baptist Hospital',
    hospitalCode: 'BBH-01',
  },
  {
    id: 'veh-amb-32',
    vehicleId: 'AMB-32',
    registrationNumber: 'KA-51-EA-3232',
    type: 'AMBULANCE',
    status: 'EN_ROUTE',
    driverName: 'Arvind Shenoy',
    driverContact: '+91 98450 32320',
    capacity: 2,
    location: { type: 'Point', coordinates: [77.6880, 12.8420] },
    speed: 52.0,
    heading: 340,
    hospitalName: 'Narayana Institute of Cardiac Sciences',
    hospitalCode: 'NAR-01',
  },
  {
    id: 'veh-amb-33',
    vehicleId: 'AMB-33',
    registrationNumber: 'KA-50-EA-3333',
    type: 'AMBULANCE',
    status: 'AVAILABLE',
    driverName: 'Bhaskar Rao',
    driverContact: '+91 98450 33330',
    capacity: 2,
    location: { type: 'Point', coordinates: [77.6180, 13.0480] },
    speed: 0,
    heading: 0,
    hospitalName: 'Aster CMI Hospital (Hebbal)',
    hospitalCode: 'AST-01',
  },
  {
    id: 'veh-amb-34',
    vehicleId: 'AMB-34',
    registrationNumber: 'KA-05-EA-3434',
    type: 'AMBULANCE',
    status: 'DISPATCHED',
    driverName: 'Guruprasad N',
    driverContact: '+91 98450 34340',
    capacity: 2,
    location: { type: 'Point', coordinates: [77.5650, 12.9050] },
    speed: 38.0,
    heading: 110,
    hospitalName: 'Apollo Hospitals Bannerghatta',
    hospitalCode: 'APO-01',
  },
  {
    id: 'veh-amb-35',
    vehicleId: 'AMB-35',
    registrationNumber: 'KA-03-EA-3535',
    type: 'AMBULANCE',
    status: 'EN_ROUTE',
    driverName: 'Rakesh Verma',
    driverContact: '+91 98450 35350',
    capacity: 1,
    location: { type: 'Point', coordinates: [77.7180, 12.9660] },
    speed: 48.0,
    heading: 80,
    hospitalName: 'Vydehi Hospital Whitefield',
    hospitalCode: 'VYD-01',
  },
  {
    id: 'veh-amb-36',
    vehicleId: 'AMB-36',
    registrationNumber: 'KA-02-EA-3636',
    type: 'AMBULANCE',
    status: 'AVAILABLE',
    driverName: 'Nagesh K',
    driverContact: '+91 98450 36360',
    capacity: 2,
    location: { type: 'Point', coordinates: [77.5450, 12.9780] },
    speed: 0,
    heading: 0,
    hospitalName: 'Victoria Hospital (Standby)',
    hospitalCode: 'VIC-01',
  },
]

export const DEMO_EMERGENCIES: Emergency[] = [
  {
    id: 'emg-demo-001',
    emergencyId: 'E-DEMO-001',
    type: 'MEDICAL',
    priority: 'CRITICAL',
    status: 'IN_PROGRESS',
    description: 'Acute ST-elevation myocardial infarction near Koramangala 4th block. Arterial green-wave corridor to Manipal Cath Lab.',
    location: { type: 'Point', coordinates: [77.6320, 12.9410] },
    destination: { type: 'Point', coordinates: [77.6483, 12.9582] },
    assignedVehicle: {
      vehicleId: 'AMB-01',
      registrationNumber: 'KA-01-EA-1001',
      status: 'EN_ROUTE',
    },
    callerName: 'Sunita Murthy',
    callerContact: '+91 98451 00111',
    createdAt: new Date(Date.now() - 15 * 60000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'emg-demo-002',
    emergencyId: 'E-DEMO-002',
    type: 'ACCIDENT',
    priority: 'CRITICAL',
    status: 'DISPATCHED',
    description: 'High-speed motorbike rollover with traumatic brain injury near RT Nagar. Level 1 trauma resuscitation at Victoria.',
    location: { type: 'Point', coordinates: [77.5890, 13.0180] },
    destination: { type: 'Point', coordinates: [77.5739, 12.9634] },
    assignedVehicle: {
      vehicleId: 'AMB-02',
      registrationNumber: 'KA-04-EA-2002',
      status: 'EN_ROUTE',
    },
    callerName: 'Traffic Inspector Hebbal',
    callerContact: '+91 98452 00222',
    createdAt: new Date(Date.now() - 25 * 60000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'emg-demo-003',
    emergencyId: 'E-DEMO-003',
    type: 'MEDICAL',
    priority: 'HIGH',
    status: 'DISPATCHED',
    description: 'Severe pediatric asthma with impending respiratory failure near Kundalahalli Gate. Pediatric ICU transfer to Sakra.',
    location: { type: 'Point', coordinates: [77.7120, 12.9650] },
    destination: { type: 'Point', coordinates: [77.6890, 12.9288] },
    assignedVehicle: {
      vehicleId: 'AMB-03',
      registrationNumber: 'KA-03-EA-3003',
      status: 'EN_ROUTE',
    },
    callerName: 'Deepa Nair',
    callerContact: '+91 98453 00333',
    createdAt: new Date(Date.now() - 10 * 60000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'emg-demo-004',
    emergencyId: 'E-DEMO-004',
    type: 'MEDICAL',
    priority: 'HIGH',
    status: 'DISPATCHED',
    description: 'Acute neurological stroke with dense hemiplegia within 2-hour window. Fast-track stroke unit at Bowring.',
    location: { type: 'Point', coordinates: [77.5900, 13.0600] },
    destination: { type: 'Point', coordinates: [77.6033, 12.9833] },
    assignedVehicle: {
      vehicleId: 'AMB-04',
      registrationNumber: 'KA-50-EA-4004',
      status: 'EN_ROUTE',
    },
    callerName: 'Kishore Kumar',
    callerContact: '+91 98454 00444',
    createdAt: new Date(Date.now() - 35 * 60000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'emg-demo-005',
    emergencyId: 'E-DEMO-005',
    type: 'ACCIDENT',
    priority: 'CRITICAL',
    status: 'DISPATCHED',
    description: 'Multi-car pileup on expressway underpass near Bommanahalli. Trapped casualties with severe crush trauma.',
    location: { type: 'Point', coordinates: [77.6400, 12.9050] },
    destination: { type: 'Point', coordinates: [77.6200, 12.9315] },
    assignedVehicle: {
      vehicleId: 'AMB-05',
      registrationNumber: 'KA-51-EA-5005',
      status: 'EN_ROUTE',
    },
    callerName: 'Highway Patrol Officer',
    callerContact: '+91 98455 00555',
    createdAt: new Date(Date.now() - 20 * 60000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'emg-demo-006',
    emergencyId: 'E-DEMO-006',
    type: 'MEDICAL',
    priority: 'HIGH',
    status: 'DISPATCHED',
    description: 'Status epilepticus in 6-year-old child near CMH Road Metro Station.',
    location: { type: 'Point', coordinates: [77.6440, 12.9780] },
    destination: { type: 'Point', coordinates: [77.6483, 12.9582] },
    assignedVehicle: {
      vehicleId: 'AMB-07',
      registrationNumber: 'KA-02-EA-7007',
      status: 'DISPATCHED',
    },
    callerName: 'Ananya Roy',
    callerContact: '+91 98456 00666',
    createdAt: new Date(Date.now() - 12 * 60000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'emg-demo-007',
    emergencyId: 'E-DEMO-007',
    type: 'MEDICAL',
    priority: 'HIGH',
    status: 'AT_SCENE',
    description: 'Acute severe bronchospasm in chronic COPD patient with oxygen saturation at 78% in HSR 27th Main.',
    location: { type: 'Point', coordinates: [77.6450, 12.9100] },
    destination: { type: 'Point', coordinates: [77.6200, 12.9315] },
    assignedVehicle: {
      vehicleId: 'AMB-09',
      registrationNumber: 'KA-01-EA-9009',
      status: 'AT_SCENE',
    },
    callerName: 'Vikas Rao',
    callerContact: '+91 98457 00777',
    createdAt: new Date(Date.now() - 18 * 60000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'emg-demo-008',
    emergencyId: 'E-DEMO-008',
    type: 'ACCIDENT',
    priority: 'CRITICAL',
    status: 'IN_PROGRESS',
    description: 'Electrical flash burn injury across face, torso and airway in factory near Marathahalli.',
    location: { type: 'Point', coordinates: [77.7050, 12.9550] },
    destination: { type: 'Point', coordinates: [77.6890, 12.9288] },
    assignedVehicle: {
      vehicleId: 'AMB-10',
      registrationNumber: 'KA-03-EA-1010',
      status: 'EN_ROUTE',
    },
    callerName: 'Factory Safety Officer',
    callerContact: '+91 98458 00888',
    createdAt: new Date(Date.now() - 22 * 60000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'emg-demo-009',
    emergencyId: 'E-DEMO-009',
    type: 'MEDICAL',
    priority: 'MEDIUM',
    status: 'DISPATCHED',
    description: 'Diabetic ketoacidosis with severe dehydration near South End Circle Jayanagar.',
    location: { type: 'Point', coordinates: [77.5800, 12.9350] },
    destination: { type: 'Point', coordinates: [77.5739, 12.9634] },
    assignedVehicle: {
      vehicleId: 'AMB-11',
      registrationNumber: 'KA-05-EA-1111',
      status: 'EN_ROUTE',
    },
    callerName: 'Lakshmi Narayan',
    callerContact: '+91 98459 00999',
    createdAt: new Date(Date.now() - 40 * 60000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'emg-demo-010',
    emergencyId: 'E-DEMO-010',
    type: 'ACCIDENT',
    priority: 'HIGH',
    status: 'DISPATCHED',
    description: 'Elderly patient fall with displaced hip fracture and severe hypotension near Sarakki Lake.',
    location: { type: 'Point', coordinates: [77.5880, 12.9020] },
    destination: { type: 'Point', coordinates: [77.5980, 12.8920] },
    assignedVehicle: {
      vehicleId: 'AMB-12',
      registrationNumber: 'KA-05-EA-1212',
      status: 'DISPATCHED',
    },
    callerName: 'Dr. Sudhir K',
    callerContact: '+91 98460 01010',
    createdAt: new Date(Date.now() - 14 * 60000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'emg-demo-011',
    emergencyId: 'E-DEMO-011',
    type: 'MEDICAL',
    priority: 'HIGH',
    status: 'DISPATCHED',
    description: 'Ventricular tachycardia with hemodynamic compromise near Navrang Circle Rajajinagar.',
    location: { type: 'Point', coordinates: [77.5580, 12.9960] },
    destination: { type: 'Point', coordinates: [77.5855, 13.0310] },
    assignedVehicle: {
      vehicleId: 'AMB-13',
      registrationNumber: 'KA-02-EA-1313',
      status: 'EN_ROUTE',
    },
    callerName: 'Meera Deshpande',
    callerContact: '+91 98461 01111',
    createdAt: new Date(Date.now() - 16 * 60000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'emg-demo-012',
    emergencyId: 'E-DEMO-012',
    type: 'MEDICAL',
    priority: 'CRITICAL',
    status: 'DISPATCHED',
    description: 'Postpartum hemorrhage with uterine atony following home delivery in Malleshwaram.',
    location: { type: 'Point', coordinates: [77.5700, 13.0030] },
    destination: { type: 'Point', coordinates: [77.5684, 13.0305] },
    assignedVehicle: {
      vehicleId: 'AMB-08',
      registrationNumber: 'KA-41-EA-8008',
      status: 'AVAILABLE',
    },
    callerName: 'Staff Nurse Geeta',
    callerContact: '+91 98462 01212',
    createdAt: new Date(Date.now() - 8 * 60000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'emg-demo-013',
    emergencyId: 'E-DEMO-013',
    type: 'MEDICAL',
    priority: 'CRITICAL',
    status: 'DISPATCHED',
    description: 'Acute thoracic aortic dissection near Banashankari 2nd Stage. Urgent cardiothoracic surgical transfer to Sagar Hospital.',
    location: { type: 'Point', coordinates: [77.5600, 12.9300] },
    destination: { type: 'Point', coordinates: [77.5560, 12.9250] },
    assignedVehicle: {
      vehicleId: 'AMB-17',
      registrationNumber: 'KA-05-EA-1717',
      status: 'AVAILABLE',
    },
    callerName: 'Dr. Ramesh Bellary',
    callerContact: '+91 98463 01313',
    createdAt: new Date(Date.now() - 5 * 60000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'emg-demo-014',
    emergencyId: 'E-DEMO-014',
    type: 'MEDICAL',
    priority: 'CRITICAL',
    status: 'DISPATCHED',
    description: 'Out-of-hospital cardiac arrest in gym facility near BTM 2nd Stage Udupi Garden.',
    location: { type: 'Point', coordinates: [77.6120, 12.9180] },
    destination: { type: 'Point', coordinates: [77.6100, 12.9150] },
    assignedVehicle: {
      vehicleId: 'AMB-18',
      registrationNumber: 'KA-01-EA-1818',
      status: 'EN_ROUTE',
    },
    callerName: 'Gym Manager Vinod',
    callerContact: '+91 98464 01414',
    createdAt: new Date(Date.now() - 7 * 60000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'emg-demo-015',
    emergencyId: 'E-DEMO-015',
    type: 'ACCIDENT',
    priority: 'CRITICAL',
    status: 'DISPATCHED',
    description: 'Multiple pedestrian collision caused by brake failure at Vijayanagar Tollgate.',
    location: { type: 'Point', coordinates: [77.5350, 12.9730] },
    destination: { type: 'Point', coordinates: [77.5739, 12.9634] },
    assignedVehicle: {
      vehicleId: 'AMB-19',
      registrationNumber: 'KA-02-EA-1919',
      status: 'DISPATCHED',
    },
    callerName: 'Traffic Constable Vijayanagar',
    callerContact: '+91 98465 01515',
    createdAt: new Date(Date.now() - 11 * 60000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'emg-demo-016',
    emergencyId: 'E-DEMO-016',
    type: 'MEDICAL',
    priority: 'HIGH',
    status: 'DISPATCHED',
    description: 'Acute necrotizing pancreatitis with severe peritoneal signs at Kalyan Nagar.',
    location: { type: 'Point', coordinates: [77.6430, 13.0180] },
    destination: { type: 'Point', coordinates: [77.6415, 13.0245] },
    assignedVehicle: {
      vehicleId: 'AMB-20',
      registrationNumber: 'KA-04-EA-2020',
      status: 'DISPATCHED',
    },
    callerName: 'Dr. Praveen Nair',
    callerContact: '+91 98466 01616',
    createdAt: new Date(Date.now() - 9 * 60000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'emg-demo-017',
    emergencyId: 'E-DEMO-017',
    type: 'ACCIDENT',
    priority: 'CRITICAL',
    status: 'DISPATCHED',
    description: 'Metro pillar staging collapse trapping construction crew near Kengeri Satellite Town.',
    location: { type: 'Point', coordinates: [77.4850, 12.9100] },
    destination: { type: 'Point', coordinates: [77.4950, 12.8950] },
    assignedVehicle: {
      vehicleId: 'AMB-21',
      registrationNumber: 'KA-05-EA-2121',
      status: 'DISPATCHED',
    },
    callerName: 'BMRCL Safety Engineer',
    callerContact: '+91 98467 01717',
    createdAt: new Date(Date.now() - 14 * 60000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'emg-demo-018',
    emergencyId: 'E-DEMO-018',
    type: 'MEDICAL',
    priority: 'CRITICAL',
    status: 'DISPATCHED',
    description: 'Severe status asthmaticus with maternal hypoxemia at Sarjapur Wipro Gate.',
    location: { type: 'Point', coordinates: [77.6950, 12.9080] },
    destination: { type: 'Point', coordinates: [77.6750, 12.9200] },
    assignedVehicle: {
      vehicleId: 'AMB-24',
      registrationNumber: 'KA-51-EA-2424',
      status: 'DISPATCHED',
    },
    callerName: 'Wipro Campus Paramedic',
    callerContact: '+91 98468 01818',
    createdAt: new Date(Date.now() - 8 * 60000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'emg-demo-019',
    emergencyId: 'E-DEMO-019',
    type: 'MEDICAL',
    priority: 'HIGH',
    status: 'DISPATCHED',
    description: 'Acute coronary syndrome with ongoing ST elevation at Banashankari BDA Complex.',
    location: { type: 'Point', coordinates: [77.5730, 12.9250] },
    destination: { type: 'Point', coordinates: [77.5600, 12.9180] },
    assignedVehicle: {
      vehicleId: 'AMB-17',
      registrationNumber: 'KA-05-EA-1717',
      status: 'DISPATCHED',
    },
    callerName: 'Dr. Girish K',
    callerContact: '+91 98469 01919',
    createdAt: new Date(Date.now() - 12 * 60000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'emg-demo-020',
    emergencyId: 'E-DEMO-020',
    type: 'ACCIDENT',
    priority: 'CRITICAL',
    status: 'DISPATCHED',
    description: 'Elevated highway collision involving heavy tanker and taxi near Electronic City Phase 2.',
    location: { type: 'Point', coordinates: [77.6850, 12.8400] },
    destination: { type: 'Point', coordinates: [77.6880, 12.8420] },
    assignedVehicle: {
      vehicleId: 'AMB-32',
      registrationNumber: 'KA-51-EA-3232',
      status: 'DISPATCHED',
    },
    callerName: 'Expressway Control Room',
    callerContact: '+91 98470 02020',
    createdAt: new Date(Date.now() - 16 * 60000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'emg-demo-021',
    emergencyId: 'E-DEMO-021',
    type: 'MEDICAL',
    priority: 'HIGH',
    status: 'DISPATCHED',
    description: 'Acute intracranial hemorrhage with deteriorating GCS at Rajajinagar Industrial Area.',
    location: { type: 'Point', coordinates: [77.5450, 12.9880] },
    destination: { type: 'Point', coordinates: [77.5855, 13.0310] },
    assignedVehicle: {
      vehicleId: 'AMB-11',
      registrationNumber: 'KA-02-EA-1111',
      status: 'DISPATCHED',
    },
    callerName: 'Industrial Health Clinic',
    callerContact: '+91 98471 02121',
    createdAt: new Date(Date.now() - 10 * 60000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'emg-demo-022',
    emergencyId: 'E-DEMO-022',
    type: 'ACCIDENT',
    priority: 'CRITICAL',
    status: 'DISPATCHED',
    description: 'Chemical ammonia vapor release with inhalation injuries at Peenya 2nd Stage.',
    location: { type: 'Point', coordinates: [77.5100, 13.0300] },
    destination: { type: 'Point', coordinates: [77.5500, 13.0220] },
    assignedVehicle: {
      vehicleId: 'AMB-22',
      registrationNumber: 'KA-04-EA-2222',
      status: 'DISPATCHED',
    },
    callerName: 'Peenya Fire Station',
    callerContact: '+91 98472 02222',
    createdAt: new Date(Date.now() - 20 * 60000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'emg-demo-023',
    emergencyId: 'E-DEMO-023',
    type: 'MEDICAL',
    priority: 'HIGH',
    status: 'DISPATCHED',
    description: 'Refractory epileptic status in 8-year-old child near Fraser Town.',
    location: { type: 'Point', coordinates: [77.6100, 12.9960] },
    destination: { type: 'Point', coordinates: [77.6033, 12.9833] },
    assignedVehicle: {
      vehicleId: 'AMB-26',
      registrationNumber: 'KA-03-EA-2626',
      status: 'DISPATCHED',
    },
    callerName: 'Dr. Reena D’Souza',
    callerContact: '+91 98473 02323',
    createdAt: new Date(Date.now() - 6 * 60000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'emg-demo-024',
    emergencyId: 'E-DEMO-024',
    type: 'ACCIDENT',
    priority: 'HIGH',
    status: 'DISPATCHED',
    description: 'Two-wheeler collision with multiple limb deformities near Nagarbhavi Circle.',
    location: { type: 'Point', coordinates: [77.5050, 12.9600] },
    destination: { type: 'Point', coordinates: [77.5080, 12.9620] },
    assignedVehicle: {
      vehicleId: 'AMB-28',
      registrationNumber: 'KA-41-EA-2828',
      status: 'DISPATCHED',
    },
    callerName: 'Traffic Police Post',
    callerContact: '+91 98474 02424',
    createdAt: new Date(Date.now() - 15 * 60000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'emg-demo-025',
    emergencyId: 'E-DEMO-025',
    type: 'MEDICAL',
    priority: 'CRITICAL',
    status: 'DISPATCHED',
    description: 'Sudden collapse with pulseless electrical activity at Manyata Tech Park Gate 1.',
    location: { type: 'Point', coordinates: [77.6160, 13.0450] },
    destination: { type: 'Point', coordinates: [77.6180, 13.0480] },
    assignedVehicle: {
      vehicleId: 'AMB-33',
      registrationNumber: 'KA-04-EA-3333',
      status: 'DISPATCHED',
    },
    callerName: 'Manyata First Responder Unit',
    callerContact: '+91 98475 02525',
    createdAt: new Date(Date.now() - 5 * 60000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
]

export const DEMO_INCIDENTS: Incident[] = [
  {
    id: 'inc-demo-01',
    incidentId: 'INC-DEMO-01',
    type: 'ACCIDENT',
    severity: 'CRITICAL',
    status: 'ACTIVE',
    description: 'Overturned commercial truck blocking 2 out of 3 lanes on Intermediate Ring Road near Domlur Flyover.',
    location: { type: 'Point', coordinates: [77.6395, 12.9510] },
    createdAt: new Date(Date.now() - 30 * 60000).toISOString(),
  },
  {
    id: 'inc-demo-02',
    incidentId: 'INC-DEMO-02',
    type: 'ROAD_CLOSURE',
    severity: 'HIGH',
    status: 'ACTIVE',
    description: 'Emergency pipeline excavation and water main burst on Palace Road near Mekhri Circle.',
    location: { type: 'Point', coordinates: [77.5850, 13.0020] },
    createdAt: new Date(Date.now() - 45 * 60000).toISOString(),
  },
  {
    id: 'inc-demo-03',
    incidentId: 'INC-DEMO-03',
    type: 'TRAFFIC_JAM',
    severity: 'CRITICAL',
    status: 'ACTIVE',
    description: 'Severe 2.4 km gridlock and broken-down BMTC bus at Marathahalli junction underpass.',
    location: { type: 'Point', coordinates: [77.6850, 12.9560] },
    createdAt: new Date(Date.now() - 25 * 60000).toISOString(),
  },
  {
    id: 'inc-demo-04',
    incidentId: 'INC-DEMO-04',
    type: 'ACCIDENT',
    severity: 'CRITICAL',
    status: 'ACTIVE',
    description: 'Multi-axle container collision at Central Silk Board junction causing standstill traffic toward Madiwala.',
    location: { type: 'Point', coordinates: [77.6320, 12.9180] },
    createdAt: new Date(Date.now() - 40 * 60000).toISOString(),
  },
  {
    id: 'inc-demo-05',
    incidentId: 'INC-DEMO-05',
    type: 'ROAD_CLOSURE',
    severity: 'MEDIUM',
    status: 'ACTIVE',
    description: 'Fallen roadside tree branches blocking left corridor lane on Indiranagar 100ft Road.',
    location: { type: 'Point', coordinates: [77.6420, 12.9720] },
    createdAt: new Date(Date.now() - 15 * 60000).toISOString(),
  },
  {
    id: 'inc-demo-06',
    incidentId: 'INC-DEMO-06',
    type: 'TRAFFIC_JAM',
    severity: 'HIGH',
    status: 'ACTIVE',
    description: 'Flash waterlogging and flooded underpass near HSR Layout 14th Main.',
    location: { type: 'Point', coordinates: [77.6380, 12.9130] },
    createdAt: new Date(Date.now() - 35 * 60000).toISOString(),
  },
  {
    id: 'inc-demo-07',
    incidentId: 'INC-DEMO-07',
    type: 'ACCIDENT',
    severity: 'HIGH',
    status: 'ACTIVE',
    description: 'Broken-down heavy dumper on elevated flyover heading toward Bellandur.',
    location: { type: 'Point', coordinates: [77.6980, 12.9500] },
    createdAt: new Date(Date.now() - 20 * 60000).toISOString(),
  },
  {
    id: 'inc-demo-08',
    incidentId: 'INC-DEMO-08',
    type: 'ROAD_WORK',
    severity: 'MEDIUM',
    status: 'ACTIVE',
    description: 'Metro line barricade repair on Bannerghatta Road near JP Nagar 3rd Phase.',
    location: { type: 'Point', coordinates: [77.5920, 12.9000] },
    createdAt: new Date(Date.now() - 50 * 60000).toISOString(),
  },
  {
    id: 'inc-demo-09',
    incidentId: 'INC-DEMO-09',
    type: 'TRAFFIC_JAM',
    severity: 'HIGH',
    status: 'ACTIVE',
    description: 'Heavy market festival crowd spillover near Malleshwaram 8th Cross circle.',
    location: { type: 'Point', coordinates: [77.5710, 13.0010] },
    createdAt: new Date(Date.now() - 10 * 60000).toISOString(),
  },
  {
    id: 'inc-demo-10',
    incidentId: 'INC-DEMO-010',
    type: 'ROAD_WORK',
    severity: 'CRITICAL',
    status: 'ACTIVE',
    description: 'Tin Factory KR Puram expansion work with major lane restriction on highway approach.',
    location: { type: 'Point', coordinates: [77.6750, 12.9980] },
    createdAt: new Date(Date.now() - 60 * 60000).toISOString(),
  },
  {
    id: 'inc-demo-11',
    incidentId: 'INC-DEMO-011',
    type: 'ROAD_CLOSURE',
    severity: 'HIGH',
    status: 'ACTIVE',
    description: 'Concrete mixer truck stall near Banashankari 100ft Ring Road junction.',
    location: { type: 'Point', coordinates: [77.5680, 12.9230] },
    createdAt: new Date(Date.now() - 22 * 60000).toISOString(),
  },
  {
    id: 'inc-demo-12',
    incidentId: 'INC-DEMO-012',
    type: 'TRAFFIC_JAM',
    severity: 'CRITICAL',
    status: 'ACTIVE',
    description: 'Peak IT corridor rush and broken traffic signal at Silk Board junction.',
    location: { type: 'Point', coordinates: [77.6230, 12.9170] },
    createdAt: new Date(Date.now() - 18 * 60000).toISOString(),
  },
  {
    id: 'inc-demo-13',
    incidentId: 'INC-DEMO-013',
    type: 'ROAD_CLOSURE',
    severity: 'HIGH',
    status: 'ACTIVE',
    description: 'Asphalt resurfacing on Mysore Road Flyover lane toward City Market.',
    location: { type: 'Point', coordinates: [77.5550, 12.9620] },
    createdAt: new Date(Date.now() - 40 * 60000).toISOString(),
  },
  {
    id: 'inc-demo-14',
    incidentId: 'INC-DEMO-014',
    type: 'ACCIDENT',
    severity: 'HIGH',
    status: 'ACTIVE',
    description: 'Bus and auto rickshaw collision on Hennur Main Road near HRBR Layout.',
    location: { type: 'Point', coordinates: [77.6400, 13.0200] },
    createdAt: new Date(Date.now() - 12 * 60000).toISOString(),
  },
  {
    id: 'inc-demo-15',
    incidentId: 'INC-DEMO-015',
    type: 'ROAD_WORK',
    severity: 'CRITICAL',
    status: 'ACTIVE',
    description: 'Excavation and crane movement near Kengeri Satellite Town metro line.',
    location: { type: 'Point', coordinates: [77.4900, 12.9050] },
    createdAt: new Date(Date.now() - 55 * 60000).toISOString(),
  },
  {
    id: 'inc-demo-16',
    incidentId: 'INC-DEMO-016',
    type: 'TRAFFIC_JAM',
    severity: 'HIGH',
    status: 'ACTIVE',
    description: 'Tech park entry backlog on Sarjapur Road near Carmelaram railway gate.',
    location: { type: 'Point', coordinates: [77.6900, 12.9100] },
    createdAt: new Date(Date.now() - 25 * 60000).toISOString(),
  },
  {
    id: 'inc-demo-17',
    incidentId: 'INC-DEMO-017',
    type: 'ACCIDENT',
    severity: 'HIGH',
    status: 'ACTIVE',
    description: 'Multi-car pileup on Hebbal Flyover ramp toward Kempegowda International Airport.',
    location: { type: 'Point', coordinates: [77.5920, 13.0360] },
    createdAt: new Date(Date.now() - 30 * 60000).toISOString(),
  },
  {
    id: 'inc-demo-18',
    incidentId: 'INC-DEMO-018',
    type: 'ROAD_CLOSURE',
    severity: 'MEDIUM',
    status: 'ACTIVE',
    description: 'BESCOM cable replacement blocking slow lane on Victoria Hospital road.',
    location: { type: 'Point', coordinates: [77.5740, 12.9640] },
    createdAt: new Date(Date.now() - 15 * 60000).toISOString(),
  },
  {
    id: 'inc-demo-19',
    incidentId: 'INC-DEMO-019',
    type: 'ACCIDENT',
    severity: 'HIGH',
    status: 'ACTIVE',
    description: 'Water tanker engine seizure on Outer Ring Road Bellandur underpass.',
    location: { type: 'Point', coordinates: [77.6780, 12.9300] },
    createdAt: new Date(Date.now() - 20 * 60000).toISOString(),
  },
  {
    id: 'inc-demo-20',
    incidentId: 'INC-DEMO-020',
    type: 'TRAFFIC_JAM',
    severity: 'CRITICAL',
    status: 'ACTIVE',
    description: 'Major traffic standstill near Manyata Tech Park Gate 1 and Nagavara junction.',
    location: { type: 'Point', coordinates: [77.6200, 13.0460] },
    createdAt: new Date(Date.now() - 10 * 60000).toISOString(),
  },
]

export const DEMO_ROUTES: Record<string, Route[]> = {
  'E-DEMO-001': [
    {
      id: 'route-demo-01',
      routeId: 'ROUTE-DEMO-01',
      emergency: 'E-DEMO-001',
      vehicle: 'AMB-DEMO-01',
      origin: { type: 'Point', coordinates: [77.6030, 12.9730] },
      destination: { type: 'Point', coordinates: [77.6483, 12.9582] },
      distance: 5500,
      duration: 600,
      distanceMeters: 5500,
      durationSeconds: 600,
      provider: 'GOOGLE',
      routeType: 'PLANNED',
      status: 'ACTIVE',
      geometry: {
        type: 'LineString',
        coordinates: [
          [77.6030, 12.9730],
          [77.6065, 12.9725],
          [77.6100, 12.9720],
          [77.6180, 12.9690],
          [77.6300, 12.9640],
          [77.6400, 12.9600],
          [77.6483, 12.9582],
        ],
      },
    },
    {
      id: 'route-demo-alt',
      routeId: 'ROUTE-DEMO-ALT',
      emergency: 'E-DEMO-001',
      vehicle: 'AMB-DEMO-01',
      origin: { type: 'Point', coordinates: [77.6030, 12.9730] },
      destination: { type: 'Point', coordinates: [77.6483, 12.9582] },
      distance: 5200,
      duration: 520,
      distanceMeters: 5200,
      durationSeconds: 520,
      provider: 'GOOGLE',
      routeType: 'ALTERNATIVE',
      status: 'ACTIVE',
      geometry: {
        type: 'LineString',
        coordinates: [
          [77.6030, 12.9730],
          [77.6135, 12.9740],
          [77.6215, 12.9750],
          [77.6320, 12.9710],
          [77.6420, 12.9620],
          [77.6483, 12.9582],
        ],
      },
    },
  ],
}

export const DEMO_TRAJECTORIES: Record<string, Trajectory[]> = {
  'AMB-DEMO-01': [
    { id: 'traj-1', vehicleId: 'AMB-DEMO-01', location: { type: 'Point', coordinates: [77.6030, 12.9730] }, speed: 45, heading: 90, timestamp: new Date(Date.now() - 80000).toISOString(), source: 'SIMULATOR', createdAt: '' },
    { id: 'traj-2', vehicleId: 'AMB-DEMO-01', location: { type: 'Point', coordinates: [77.6065, 12.9725] }, speed: 26, heading: 95, timestamp: new Date(Date.now() - 60000).toISOString(), source: 'SIMULATOR', createdAt: '' },
    { id: 'traj-3', vehicleId: 'AMB-DEMO-01', location: { type: 'Point', coordinates: [77.6100, 12.9720] }, speed: 11, heading: 100, timestamp: new Date(Date.now() - 40000).toISOString(), source: 'SIMULATOR', createdAt: '' },
    { id: 'traj-4', vehicleId: 'AMB-DEMO-01', location: { type: 'Point', coordinates: [77.6135, 12.9740] }, speed: 32, heading: 45, timestamp: new Date(Date.now() - 20000).toISOString(), source: 'SIMULATOR', createdAt: '' },
    { id: 'traj-5', vehicleId: 'AMB-DEMO-01', location: { type: 'Point', coordinates: [77.6175, 12.9755] }, speed: 38, heading: 85, timestamp: new Date().toISOString(), source: 'SIMULATOR', createdAt: '' },
  ],
}

export const DEMO_DEVIATION = {
  status: 'DEVIATED',
  distanceFromRouteMeters: 175,
  bearingDivergenceDegrees: 35,
  isDeviated: true,
  riskLevel: 'HIGH',
  evaluatedAt: new Date().toISOString(),
}

export const DEMO_PREDICTION = {
  predictedArrival: new Date(Date.now() + 10 * 60000).toISOString(),
  predictedDelayMinutes: 8.4,
  delayRisk: 'HIGH',
  routeRisk: 'HIGH',
  confidenceScore: 0.88,
  rerouteAdvised: true,
  recommendedRouteId: 'ROUTE-DEMO-ALT',
  estimatedTimeSavedMinutes: 6.0,
  factors: [
    { factor: 'Trinity Overpass Incident Congestion', impact: '+5.2m', epistemicType: 'OBSERVED' },
    { factor: 'Vehicle Deceleration on Approach', impact: '+3.2m', epistemicType: 'OBSERVED' },
    { factor: 'V2X Green-Wave Corridor Bypass', impact: '-1.6m', epistemicType: 'INFERRED' },
  ],
}

export const DEMO_DECISION = {
  decisionId: 'DEC-DEMO-01',
  emergencyId: 'E-DEMO-001',
  vehicleId: 'AMB-DEMO-01',
  routeId: 'ROUTE-DEMO-01',
  primaryAction: 'REROUTE',
  action: 'REROUTE',
  severity: 'CRITICAL',
  status: 'PENDING_OPERATOR_ACTION',
  reasonCodes: ['CORRIDOR_BLOCKED', 'PREDICTION_CRITICAL_DELAY', 'ALTERNATIVE_ROUTE_AVAILABLE'],
  situationHash: 'cbbd815596b7596e',
  details: {
    summary: 'Reroute to Alternative Bypass ROUTE-DEMO-ALT via 100ft Rd',
    reasoning: [
      'Incident INC-DEMO-01 caused 8.4m predicted delay on primary corridor.',
      'Alternative route ROUTE-DEMO-ALT saves ~6 minutes with V2X signal clearance.',
      'Awaiting control room operator authorization.',
    ],
  },
  evaluatedAt: new Date().toISOString(),
}
